version: 0.1
os: linux
files:
  - source: /Pase
    destination: /home/pasatupase/demo
hooks:
  AfterInstall:
    - location: scripts/after.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
      runas: root
